# The meta-data of site.
# © 2017-2019 Cotes Chung
# MIT License

ga_id: "your_google_analytics_id"

disqus_shortname: "lkighy"   # Change to your Disqus shortname.

first_run: 2019                   # The year your website was first run.

uri: "https://lkighy.github.io"  # Replace with your domain, e.g. "https://username.github.io"
